volumes:
  markflow_local_postgres_data: {}
  markflow_local_postgres_data_backups: {}
  

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: markflow_local_django
    container_name: markflow_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: markflow_production_postgres
    container_name: markflow_local_postgres
    volumes:
      - markflow_local_postgres_data:/var/lib/postgresql/data
      - markflow_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
